// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phmbofzvpiqpgtyhkoov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobWJvZnp2cGlxcGd0eWhrb292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzE2NzAsImV4cCI6MjA2OTkwNzY3MH0.j6nBVL90z5kUovUI9Htbhofde5vASD-nXbmP1Z1bqsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});